server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
    minimumIdle: 2
    idleTimeout: 30000
  cloud:
    config:
      enabled: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE
